## eric-enmsg-pushservice image version

global:
  pullSecret:
  registry:
    url: armdocker.rnd.ericsson.se
  ingress:
    enmHost:
  enmProperties:
    COM_INF_LDAP_ADMIN_ACCESS:
    COM_INF_LDAP_PORT:
    COM_INF_LDAP_ROOT_SUFFIX:
    COM_INF_LDAP_ADMIN_CN:
    LDAP_ADMIN_CN:
    LDAP_ADMIN_PASSWORD:
    pmicNfsShareList:
    postgres_service:
    UI_PRES_SERVER:
    pmserv: pmserv
  timezone:
productNumber: CXD 101 1159
productRevision: RSTATE
labels: {}
securityPolicy:
  rolename: pushservice
# Number of replicas(pods) to deploy
replicas-eric-enmsg-pushservice: 1
images:
  eric-enmsg-pushservice:
    name: eric-enmsg-pushservice
    tag: VERSION
  waitInitContainer:
    enabled: true
    name: eric-enm-init-container
    tag: 1.64.0-32
    command: "[ '/bin/sh', '-c', 'bash /var/tmp/check_service.sh -s gossiprouter-cache,gossiprouter-eap7,jms01,postgres,sps,pmserv,eric-enm-modeldeployservice'
      ]"
  eric-enm-monitoring:
    enabled: true
    name: eric-enm-monitoring-eap7
    tag: 1.64.0-33
  waitForCertificatesContainer:
    enabled: true
    name: enm-wait-for-certificates-container
    tag: 1.52.0-33
imageCredentials:
  repoPath: proj-enm
  pullPolicy: IfNotPresent
  pullSecret:
  registry:
    url:
eric-enm-common-helmchart-library:
  enabled: true
## Configure the service
service:
  name: pushservice
  sgname: pushservice
  annotations: {}
  labels:
  xmlMountPath: "/ericsson/credm/certReqMount"
  tlsMountPath: "/ericsson/credm/tlsMount"
ingress:
  enabled: false
ingress_jboss_web_context:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
## Configure resource requests and limits
resources:
  requests:
    enabled: true
    memory: 4620Mi
    cpu: 500m
  limits:
    enabled: true
    memory: 4620Mi
    cpu: 2000m
  monitoring:
    enabled: true
    requests:
      memory: 200Mi
      cpu: 50m
    limits:
      memory: 300Mi
      cpu: 200m
probes:
  container:
    startupProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 10
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 20
    livenessProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 60
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 2
    readinessProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 30
      failureThreshold: 20
  monitoringcontainer:
    startupProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 10
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 20
    livenessProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 60
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 2
startupProbe:
  enabled: true
  command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
  arguments: --exec_agents
  initialDelaySeconds: 10
  timeoutSeconds: 30
  periodSeconds: 30
  failureThreshold: 20
# LivenessProbe Health Check configuration.
livenessProbe:
  enabled: true
  command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
  arguments: --exec_agents
  initialDelaySeconds: 60
  timeoutSeconds: 30
  periodSeconds: 30
  failureThreshold: 2
readinessProbe:
  enabled: true
  command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
  arguments: --exec_agents
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 20
# Extra Annotations to be added to pod
podAnnotations: {}
## Tolerations for pod assignment
tolerations: []
## Affinity for pod assignment
affinity: requiredDuringSchedulingIgnoredDuringExecution
# Constrain which nodes your pod is eligible to be scheduled on
nodeAffinity: {}
priorityClassName: ""
## Node selector
nodeSelector: {}
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0
## Pod Disruption Budget is an indicator of the number of disruptions that can be tolerated at a given time.
podDisruptionBudget:
  maxUnavailable: 1
credmController:
  name: eric-enm-credm-controller
  port: 5001
jobs:
  jobAction: certrequest
  certRequest:
    imageName: enm-certrequestjob-container
    pullPolicy: IfNotPresent
    tag: 1.52.0-33
    resources:
      requests:
        enabled: true
        cpu: 50m
        memory: 218Mi
      limits:
        enabled: true
        cpu: 500m
        memory: 512Mi
securityContext:
  supplementalGroups:
  - 0
  - 205
  - 206
  - 5000
  pushservice:
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    capabilities:
      drop:
      - ALL
  monitoring:
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    capabilities:
      drop:
      - ALL
  waitInitContainer:
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      drop:
      - ALL
  waitForCertificatesContainer:
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    capabilities:
      drop:
      - ALL
